version: '3'

dotenv: ['.env']
silent: true


tasks:
  default:
    desc: prints this help
    cmd: task -l
  
  build-vm:
    desc: build vm
    dir: ./nixos
    cmd: nixos-rebuild build-vm --flake .#vm --override-input nixpkgs nixpkgs
  
  vm:
    desc: enter vm
    cmd: ./nixos/result/bin/run-nixos-vm -nographic

  build-container:
    desc: build container
    dir: ./nixos
    cmd: sudo nixos-container create local-ai --ensure-unique-name --flake .#container --override-input nixpkgs nixpkgs
